export default {
  receiver_name: null,
  receiver_etnia: 'Parda',
  receiver_ascendance: 'Italiana',
  receiver_blood_type: 'a+',
  receiver_height: 1.78,
  receiver_weight: 78.5,
  receiver_hair_color: 'castanho-claro',
  receiver_eye_color: 'verde',
  receiver_hair_properties: 'ondulado',
  receiver_skin_tone: 'branca-b',
  receiver_picture: null,
  partner_name: 'Marcos Antônio',
  partner_etnia: 'branco',
  partner_ascendance: 'Português',
  partner_blood_type: 'o-',
  partner_height: 1.84,
  partner_weight: 98.5,
  partner_hair_color: 'castanho-claro',
  partner_eye_color: 'verde',
  partner_hair_properties: 'ondulado',
  partner_skin_tone: 'branca-b',
  partner_picture: null,
  notes: null,
  validation_cicle_type: null,
  validation_addition: null,
  validation_obs: null,
  doctor: null,
  unit: null,
  treatment_type: null,
  blood_compatibility: null,
  is_valid: null,
  status: null,
  expiration_date: null,
};
