import * as Yup from 'yup';

export default Yup.object().shape({
  health_problem: Yup.boolean().required('Campo obrigatório'),
  health_problem_details: Yup.string(),
  medication: Yup.boolean().required('Campo obrigatório'),
  medication_details: Yup.string(),
  contraceptive: Yup.boolean().required('Campo obrigatório'),
  contraceptive_details: Yup.string(),
  smoking: Yup.boolean().required('Campo obrigatório'),
  smoking_details: Yup.string(),
  surgery: Yup.boolean().required('Campo obrigatório'),
  surgery_details: Yup.string(),
  children: Yup.boolean().required('Campo obrigatório'),
  children_value: Yup.string(),
  abortion: Yup.boolean().required('Campo obrigatório'),
  abortion_details: Yup.string(),
  drugs: Yup.boolean().required('Campo obrigatório'),
  drugs_details: Yup.string(),
  psychiatric_treatment: Yup.boolean().required('Campo obrigatório'),
  psychiatric_treatment_details: Yup.string(),
  ovule_preserving: Yup.boolean().required('Campo obrigatório'),
  ovule_preserving_details: Yup.string(),
  ovule_donor: Yup.boolean().required('Campo obrigatório'),
  ovule_donor_details: Yup.string(),
  depression: Yup.boolean().required('Campo obrigatório'),
  depression_details: Yup.string(),
  inheriting_desease: Yup.boolean().required('Campo obrigatório'),
  inheriting_desease_details: Yup.string(),
  cancer: Yup.boolean().required('Campo obrigatório'),
  cancer_details: Yup.string(),
  sterile: Yup.boolean().required('Campo obrigatório'),
  sterile_details: Yup.string(),
  weight: Yup.string().required('Campo obrigatório'),
  height: Yup.string().required('Campo obrigatório'),
  arterial_press: Yup.string().required('Campo obrigatório'),
  obs: Yup.string().required('Campo obrigatório')
});
